name: bup-storage-test

on:
  pull_request:
  push:

jobs:
  bup:
    runs-on: ubuntu-latest
    env:
      CI_JOB_IMAGE: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ci/install-dependencies.sh
      - run: make
      - run: |
          cd t && \
          ./t0000-basic.sh -v && \
          ./t0001-init.sh -v && \
          ./t9904-bup-storage.sh -v && \
          ./t9905-bup-chunk-reuse.sh -v && \
          ./t9906-bup-repack-fsck.sh -v && \
          ./t9907-bup-edit-loop.sh -v
